version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    ports:
      - 5432:5432
    environment:
      MONGO_INITDB_ROOT_USERNAME: test
      MONGO_INITDB_ROOT_PASSWORD: etest
    volumes:
      - myapp:/home/node/app
volumes:
  myapp: